"""Keep the last published archive usable when a rebuild fails."""

from __future__ import annotations

import os
import shutil
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


BUILD_MARKER = ".build_in_progress"

# These are generated by the build itself. Human edits, downloaded sources and
# translation checkpoints deliberately remain outside the rollback set.
ARCHIVE_FILES = (
    "manifest.json",
    "manifest.csv",
    "bilingual_index_corrected.csv",
    "timeline_resolved.json",
    "HSR_Voice_Archive.srt",
    "HSR_Voice_Archive.ass",
    "HSR_Voice_Archive_Black.mkv",
    "ass_layout_overflow_report.json",
    "build_report.json",
    "continuous.flac",
)
PUBLISHED_STAGES = (
    "stages/05_manifest.json",
    "stages/06_audio_state.json",
    "stages/final_report.json",
)


@contextmanager
def preserve_published_archive(output: Path, state: Path) -> Iterator[None]:
    """Restore the old coherent artifact set on an ordinary build failure.

    The large audio/video outputs are replaced or removed by the builder, so
    hard links can preserve them without copying gigabytes. Text artifacts
    are copied because some CSV writers overwrite their existing inode.
    """
    output.mkdir(parents=True, exist_ok=True)
    marker = output / BUILD_MARKER
    previously_interrupted = marker.exists()
    paths = [output / name for name in ARCHIVE_FILES]
    paths.extend(state / name for name in PUBLISHED_STAGES)
    with tempfile.TemporaryDirectory(prefix=".hsr-published-", dir=output.parent) as td:
        backup = Path(td)
        originals: dict[Path, Path | None] = {}
        for index, path in enumerate(paths):
            saved = backup / str(index)
            if path.is_file():
                if path.name in {"continuous.flac", "HSR_Voice_Archive_Black.mkv"}:
                    try:
                        os.link(path, saved)
                    except OSError:
                        shutil.copy2(path, saved)
                else:
                    shutil.copy2(path, saved)
                originals[path] = saved
            else:
                originals[path] = None
        marker.touch(exist_ok=True)
        try:
            yield
        except BaseException:
            try:
                for path, saved in originals.items():
                    if saved is None:
                        path.unlink(missing_ok=True)
                    else:
                        path.parent.mkdir(parents=True, exist_ok=True)
                        os.replace(saved, path)
            except BaseException:
                # Keep the marker: the user must not see a mixed output as a
                # successfully completed archive if restoration also fails.
                raise
            if not previously_interrupted:
                marker.unlink(missing_ok=True)
            raise
        else:
            marker.unlink(missing_ok=True)
